// AUTO-GENERATED by scripts/generate-map.ts — do not edit manually
export const GEO_EXTREMES = {
  west:  "Santiago de Compostela, Spain",
  east:  "Istanbul, Turkey",
  north: "Kuopio, Finland",
  south: "Malaga, Spain",
  westCountry:  "Spain",
  eastCountry:  "Turkey",
  northCountry: "Finland",
  southCountry: "Spain",
} as const;
